# Generated by Django 5.2.4 on 2025-08-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
